let a, b, c;
a = 5;
b = 6;
c = a + b;
document.getElementById("1").innerHTML = c;
a = 10.5;
b = 7;
c = a + b;
document.getElementById("2").innerHTML = c;
a = "Tapio";
b = "opettaa";
c = a + b;
document.getElementById("3").innerHTML = c;
a = "Tapio";
b = "opettaa";
c = a + " " + b;
document.getElementById("4").innerHTML = c;
